// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// daemonDao is the data access object for the table system_daemon.
// You can define custom methods on it to extend its functionality as needed.
type daemonDao struct {
	*internal.DaemonDao
}

var (
	// Daemon is a globally accessible object for table system_daemon operations.
	Daemon = daemonDao{internal.NewDaemonDao()}
)

// Add your custom methods and functionality below.
