// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// domainDao is the data access object for the table system_domain.
// You can define custom methods on it to extend its functionality as needed.
type domainDao struct {
	*internal.DomainDao
}

var (
	// Domain is a globally accessible object for table system_domain operations.
	Domain = domainDao{internal.NewDomainDao()}
)

// Add your custom methods and functionality below.
