// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// planDao is the data access object for the table system_plan.
// You can define custom methods on it to extend its functionality as needed.
type planDao struct {
	*internal.PlanDao
}

var (
	// Plan is a globally accessible object for table system_plan operations.
	Plan = planDao{internal.NewPlanDao()}
	// SystemPlan is an alias for Plan (used by codegen-generated code).
	SystemPlan = Plan
)

// Add your custom methods and functionality below.
