// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// tenantPlanDao is the data access object for the table system_tenant_plan.
// You can define custom methods on it to extend its functionality as needed.
type tenantPlanDao struct {
	*internal.TenantPlanDao
}

var (
	// TenantPlan is a globally accessible object for table system_tenant_plan operations.
	TenantPlan = tenantPlanDao{internal.NewTenantPlanDao()}
	// SystemTenantPlan is an alias for TenantPlan (used by codegen-generated code).
	SystemTenantPlan = TenantPlan
)

// Add your custom methods and functionality below.
