// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/system/internal/dao/internal"
)

// tenantDao is the data access object for the table system_tenant.
// You can define custom methods on it to extend its functionality as needed.
type tenantDao struct {
	*internal.TenantDao
}

var (
	// Tenant is a globally accessible object for table system_tenant operations.
	Tenant = tenantDao{internal.NewTenantDao()}
)

// Add your custom methods and functionality below.
