// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoCustomerDao is the data access object for the table demo_customer.
// You can define custom methods on it to extend its functionality as needed.
type demoCustomerDao struct {
	*internal.DemoCustomerDao
}

var (
	// DemoCustomer is a globally accessible object for table demo_customer operations.
	DemoCustomer = demoCustomerDao{internal.NewDemoCustomerDao()}
)

// Add your custom methods and functionality below.
