// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoProductDao is the data access object for the table demo_product.
// You can define custom methods on it to extend its functionality as needed.
type demoProductDao struct {
	*internal.DemoProductDao
}

var (
	// DemoProduct is a globally accessible object for table demo_product operations.
	DemoProduct = demoProductDao{internal.NewDemoProductDao()}
)

// Add your custom methods and functionality below.
