// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoAppointmentDao is the data access object for the table demo_appointment.
// You can define custom methods on it to extend its functionality as needed.
type demoAppointmentDao struct {
	*internal.DemoAppointmentDao
}

var (
	// DemoAppointment is a globally accessible object for table demo_appointment operations.
	DemoAppointment = demoAppointmentDao{internal.NewDemoAppointmentDao()}
)

// Add your custom methods and functionality below.
