// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoSurveyDao is the data access object for the table demo_survey.
// You can define custom methods on it to extend its functionality as needed.
type demoSurveyDao struct {
	*internal.DemoSurveyDao
}

var (
	// DemoSurvey is a globally accessible object for table demo_survey operations.
	DemoSurvey = demoSurveyDao{internal.NewDemoSurveyDao()}
)

// Add your custom methods and functionality below.
