// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoWorkOrderDao is the data access object for the table demo_work_order.
// You can define custom methods on it to extend its functionality as needed.
type demoWorkOrderDao struct {
	*internal.DemoWorkOrderDao
}

var (
	// DemoWorkOrder is a globally accessible object for table demo_work_order operations.
	DemoWorkOrder = demoWorkOrderDao{internal.NewDemoWorkOrderDao()}
)

// Add your custom methods and functionality below.
