// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoContractDao is the data access object for the table demo_contract.
// You can define custom methods on it to extend its functionality as needed.
type demoContractDao struct {
	*internal.DemoContractDao
}

var (
	// DemoContract is a globally accessible object for table demo_contract operations.
	DemoContract = demoContractDao{internal.NewDemoContractDao()}
)

// Add your custom methods and functionality below.
