// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoAuditLogDao is the data access object for the table demo_audit_log.
// You can define custom methods on it to extend its functionality as needed.
type demoAuditLogDao struct {
	*internal.DemoAuditLogDao
}

var (
	// DemoAuditLog is a globally accessible object for table demo_audit_log operations.
	DemoAuditLog = demoAuditLogDao{internal.NewDemoAuditLogDao()}
)

// Add your custom methods and functionality below.
