// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoCategoryDao is the data access object for the table demo_category.
// You can define custom methods on it to extend its functionality as needed.
type demoCategoryDao struct {
	*internal.DemoCategoryDao
}

var (
	// DemoCategory is a globally accessible object for table demo_category operations.
	DemoCategory = demoCategoryDao{internal.NewDemoCategoryDao()}
)

// Add your custom methods and functionality below.
