// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoOrderDao is the data access object for the table demo_order.
// You can define custom methods on it to extend its functionality as needed.
type demoOrderDao struct {
	*internal.DemoOrderDao
}

var (
	// DemoOrder is a globally accessible object for table demo_order operations.
	DemoOrder = demoOrderDao{internal.NewDemoOrderDao()}
)

// Add your custom methods and functionality below.
