// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/demo/internal/dao/internal"
)

// demoCampaignDao is the data access object for the table demo_campaign.
// You can define custom methods on it to extend its functionality as needed.
type demoCampaignDao struct {
	*internal.DemoCampaignDao
}

var (
	// DemoCampaign is a globally accessible object for table demo_campaign operations.
	DemoCampaign = demoCampaignDao{internal.NewDemoCampaignDao()}
)

// Add your custom methods and functionality below.
