// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberContractDao is the data access object for the table member_contract.
// You can define custom methods on it to extend its functionality as needed.
type memberContractDao struct {
	*internal.MemberContractDao
}

var (
	// MemberContract is a globally accessible object for table member_contract operations.
	MemberContract = memberContractDao{internal.NewMemberContractDao()}
)

// Add your custom methods and functionality below.
