// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberWalletDao is the data access object for the table member_wallet.
// You can define custom methods on it to extend its functionality as needed.
type memberWalletDao struct {
	*internal.MemberWalletDao
}

var (
	// MemberWallet is a globally accessible object for table member_wallet operations.
	MemberWallet = memberWalletDao{internal.NewMemberWalletDao()}
)

// Add your custom methods and functionality below.
