// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberShopOrderDao is the data access object for the table member_shop_order.
// You can define custom methods on it to extend its functionality as needed.
type memberShopOrderDao struct {
	*internal.MemberShopOrderDao
}

var (
	// MemberShopOrder is a globally accessible object for table member_shop_order operations.
	MemberShopOrder = memberShopOrderDao{internal.NewMemberShopOrderDao()}
)

// Add your custom methods and functionality below.
