// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberWarehouseGoodsDao is the data access object for the table member_warehouse_goods.
// You can define custom methods on it to extend its functionality as needed.
type memberWarehouseGoodsDao struct {
	*internal.MemberWarehouseGoodsDao
}

var (
	// MemberWarehouseGoods is a globally accessible object for table member_warehouse_goods operations.
	MemberWarehouseGoods = memberWarehouseGoodsDao{internal.NewMemberWarehouseGoodsDao()}
)

// Add your custom methods and functionality below.
