// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberBusinessConfigDao is the data access object for the table member_business_config.
// You can define custom methods on it to extend its functionality as needed.
type memberBusinessConfigDao struct {
	*internal.MemberBusinessConfigDao
}

var (
	// MemberBusinessConfig is a globally accessible object for table member_business_config operations.
	MemberBusinessConfig = memberBusinessConfigDao{internal.NewMemberBusinessConfigDao()}
)

// Add your custom methods and functionality below.
