// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberWarehouseTradeDao is the data access object for the table member_warehouse_trade.
// You can define custom methods on it to extend its functionality as needed.
type memberWarehouseTradeDao struct {
	*internal.MemberWarehouseTradeDao
}

var (
	// MemberWarehouseTrade is a globally accessible object for table member_warehouse_trade operations.
	MemberWarehouseTrade = memberWarehouseTradeDao{internal.NewMemberWarehouseTradeDao()}
)

// Add your custom methods and functionality below.
