// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberShopCategoryDao is the data access object for the table member_shop_category.
// You can define custom methods on it to extend its functionality as needed.
type memberShopCategoryDao struct {
	*internal.MemberShopCategoryDao
}

var (
	// MemberShopCategory is a globally accessible object for table member_shop_category operations.
	MemberShopCategory = memberShopCategoryDao{internal.NewMemberShopCategoryDao()}
)

// Add your custom methods and functionality below.
