// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberContractTemplateDao is the data access object for the table member_contract_template.
// You can define custom methods on it to extend its functionality as needed.
type memberContractTemplateDao struct {
	*internal.MemberContractTemplateDao
}

var (
	// MemberContractTemplate is a globally accessible object for table member_contract_template operations.
	MemberContractTemplate = memberContractTemplateDao{internal.NewMemberContractTemplateDao()}
)

// Add your custom methods and functionality below.
