// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberShopGoodsDao is the data access object for the table member_shop_goods.
// You can define custom methods on it to extend its functionality as needed.
type memberShopGoodsDao struct {
	*internal.MemberShopGoodsDao
}

var (
	// MemberShopGoods is a globally accessible object for table member_shop_goods operations.
	MemberShopGoods = memberShopGoodsDao{internal.NewMemberShopGoodsDao()}
)

// Add your custom methods and functionality below.
