// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberTeamExportDao is the data access object for the table member_team_export.
// You can define custom methods on it to extend its functionality as needed.
type memberTeamExportDao struct {
	*internal.MemberTeamExportDao
}

var (
	// MemberTeamExport is a globally accessible object for table member_team_export operations.
	MemberTeamExport = memberTeamExportDao{internal.NewMemberTeamExportDao()}
)

// Add your custom methods and functionality below.
