// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberWalletLogDao is the data access object for the table member_wallet_log.
// You can define custom methods on it to extend its functionality as needed.
type memberWalletLogDao struct {
	*internal.MemberWalletLogDao
}

var (
	// MemberWalletLog is a globally accessible object for table member_wallet_log operations.
	MemberWalletLog = memberWalletLogDao{internal.NewMemberWalletLogDao()}
)

// Add your custom methods and functionality below.
