// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberLevelDao is the data access object for the table member_level.
// You can define custom methods on it to extend its functionality as needed.
type memberLevelDao struct {
	*internal.MemberLevelDao
}

var (
	// MemberLevel is a globally accessible object for table member_level operations.
	MemberLevel = memberLevelDao{internal.NewMemberLevelDao()}
)

// Add your custom methods and functionality below.
