// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberWarehouseListingDao is the data access object for the table member_warehouse_listing.
// You can define custom methods on it to extend its functionality as needed.
type memberWarehouseListingDao struct {
	*internal.MemberWarehouseListingDao
}

var (
	// MemberWarehouseListing is a globally accessible object for table member_warehouse_listing operations.
	MemberWarehouseListing = memberWarehouseListingDao{internal.NewMemberWarehouseListingDao()}
)

// Add your custom methods and functionality below.
