// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberRebindLogDao is the data access object for the table member_rebind_log.
// You can define custom methods on it to extend its functionality as needed.
type memberRebindLogDao struct {
	*internal.MemberRebindLogDao
}

var (
	// MemberRebindLog is a globally accessible object for table member_rebind_log operations.
	MemberRebindLog = memberRebindLogDao{internal.NewMemberRebindLogDao()}
)

// Add your custom methods and functionality below.
