// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberUserDao is the data access object for the table member_user.
// You can define custom methods on it to extend its functionality as needed.
type memberUserDao struct {
	*internal.MemberUserDao
}

var (
	// MemberUser is a globally accessible object for table member_user operations.
	MemberUser = memberUserDao{internal.NewMemberUserDao()}
)

// Add your custom methods and functionality below.
