// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gbaseadmin/app/member/internal/dao/internal"
)

// memberLevelLogDao is the data access object for the table member_level_log.
// You can define custom methods on it to extend its functionality as needed.
type memberLevelLogDao struct {
	*internal.MemberLevelLogDao
}

var (
	// MemberLevelLog is a globally accessible object for table member_level_log operations.
	MemberLevelLog = memberLevelLogDao{internal.NewMemberLevelLogDao()}
)

// Add your custom methods and functionality below.
