export const supportedBaseAdminComponents = [
  'Input',
  'InputNumber',
  'Textarea',
  'Switch',
  'Radio',
  'Select',
  'TreeSelectSingle',
  'TreeSelectMulti',
  'SelectMulti',
  'ImageUpload',
  'FileUpload',
  'RichText',
  'JsonEditor',
  'Password',
  'InputUrl',
  'DateTimePicker',
  'IconPicker',
] as const;
